spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:;INIT=CREATE SCHEMA IF NOT EXISTS point;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: sa
    password: sa
  thymeleaf:
      prefix : classpath:templates/
      check-template-location : true
      suffix : .html
      mode : HTML5
      cache : false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    Exposed: DEBUG