spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:;INIT=CREATE SCHEMA IF NOT EXISTS point;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: sa
    password: sa
  thymeleaf:
      prefix : classpath:templates/
      check-template-location : true
      suffix : .html
      mode : HTML5
      cache : false
      order : 0
  exposed:
    generate-ddl: true
logging:
  level:
    Exposed: DEBUG